apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: game-secrets
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: game-secrets
  refreshInterval: 1h
  data:
  - secretKey: JWT_SIGNING_KEY
    remoteRef:
      key: game-prod-jwt-signing-key
  - secretKey: DATABASE_URL
    remoteRef:
      key: game-prod-database-url
  - secretKey: REDIS_ADDR
    remoteRef:
      key: game-prod-redis-addr
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: game-prod-redis-password
