apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matchmaker
  template:
    metadata:
      labels:
        app: matchmaker
    spec:
      containers:
      - name: matchmaker
        image: game/matchmaker:latest
        ports:
        - containerPort: 8082
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: APP_ENV
        - name: REDIS_ADDR
          valueFrom:
            secretKeyRef:
              name: game-secrets
              key: REDIS_ADDR
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: game-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /livez
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
